[project]
name = "aysnc-quote-or-joke-fetcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "jokeapi>=1.0.5",
    "pandas>=2.3.0",
]
